import { z } from "zod";

export const ApiResponseSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>
  z.union([
    z.object({
      ok: z.literal(true),
      data: dataSchema,
    }),
    z.object({
      ok: z.literal(false),
      error: z.object({
        code: z.string(),
        message: z.string(),
      }),
    }),
  ]);

export type ApiResponse<T> =
  | { ok: true; data: T }
  | { ok: false; error: { code: string; message: string } };

/** The bounds used by every user-selected list size. */
export const LimitQuerySchema = z.coerce
  .number()
  .int()
  .min(1)
  .max(200)
  .default(100);

export type LimitQuery = z.infer<typeof LimitQuerySchema>;

/**
 * Comment ids are generated by the server, but still bounded at every route
 * boundary so an arbitrary path segment never reaches a database lookup.
 */
export const CommentIdSchema = z.string().trim().min(1).max(64);

export type CommentId = z.infer<typeof CommentIdSchema>;

export const COMMENT_REPLY_MAX_LENGTH = 4000;

export const AdminReplyInputSchema = z.object({
  body: z.string().trim().min(1).max(COMMENT_REPLY_MAX_LENGTH),
});

export type AdminReplyInput = z.infer<typeof AdminReplyInputSchema>;

/** Signed notification links are longer than newsletter's random tokens. */
export const CommentNotificationTokenQuerySchema = z.object({
  token: z.string().min(1).max(256),
});

export type CommentNotificationTokenQuery = z.infer<
  typeof CommentNotificationTokenQuerySchema
>;

/**
 * The trap field is validated separately so its presence stays out of the
 * public comment input shape while malformed JSON fields still fail closed.
 */
export const HoneypotInputSchema = z
  .object({ website: z.string().optional() })
  .passthrough();
