import type { UIDictionary } from "./types.js";

export const en: UIDictionary = {
  "nav.home": "Home",
  "nav.about": "About",
  "nav.admin": "Admin",
  "nav.search": "Search",
  "nav.back": "Back",

  "desk.readArticle": "Read article",
  "desk.minRead": "min read",
  "desk.scrollLeft": "Scroll",
  "desk.scrollRight": "Scroll",
  "desk.clickToRead": "Click the card to read",
  "desk.focusedCard": "Focused card",

  "article.back": "Back",
  "article.share": "Share",
  "article.category": "Category",
  "article.tags": "Tags",
  "article.published": "Published",
  "article.updated": "Updated",

  "comment.name": "Name",
  "comment.email": "Email",
  "comment.body": "Comment",
  "comment.submit": "Submit",
  "comment.placeholder": "Write a comment...",
  "comment.noComments": "No comments yet. Be the first to share your thoughts.",
  "comment.pending": "Pending moderation",
  "comment.approved": "Approved",
  "comment.hidden": "Hidden",
  "comment.reply": "Reply",
  "comment.report": "Report",

  "admin.title": "Admin Dashboard",
  "admin.pendingComments": "Pending Comments",
  "admin.approvedComments": "Approved Comments",
  "admin.subscribers": "Subscribers",
  "admin.approve": "Approve",
  "admin.hide": "Hide",
  "admin.delete": "Delete",
  "admin.spam": "Spam",
  "admin.reply": "Reply",
  "admin.sendNewsletter": "Send Newsletter",

  "common.loading": "Loading...",
  "common.error": "Something went wrong.",
  "common.close": "Close",
  "common.open": "Open",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.yes": "Yes",
  "common.no": "No",
  "common.confirm": "Confirm",
  "common.success": "Success",
};
