import type { UIDictionary } from "./types.js";

export const en: UIDictionary = {
  "nav.home": "Home",
  "nav.about": "About",
  "nav.admin": "Admin",
  "nav.search": "Search",
  "nav.back": "Back",

  "desk.readArticle": "Read article",
  "desk.minRead": "min read",
  "desk.scrollLeft": "Scroll",
  "desk.scrollRight": "Scroll",
  "desk.clickToRead": "Click the card to read",
  "desk.focusedCard": "Focused card",

  "article.back": "Back",
  "article.share": "Share",
  "article.category": "Category",
  "article.tags": "Tags",
  "article.published": "Published",
  "article.updated": "Updated",

  "comment.name": "Name",
  "comment.email": "Email",
  "comment.body": "Comment",
  "comment.submit": "Submit",
  "comment.placeholder": "Write a comment...",
  "comment.noComments": "No comments yet. Be the first to share your thoughts.",
  "comment.pending": "Pending moderation",
  "comment.approved": "Approved",
  "comment.hidden": "Hidden",
  "comment.reply": "Reply",
  "comment.report": "Report",
  "comment.title": "Comments",
  "comment.loading": "Loading comments…",
  "comment.posted": "Thanks — your comment is waiting to be reviewed.",
  "comment.emailHint": "Optional, and never published.",
  "comment.closed": "Comments are not open yet.",
  "comment.error": "That did not go through. Please try again.",

  "newsletter.title": "Newsletter",
  "newsletter.intro":
    "Occasional letters when there is something worth writing down. No schedule.",
  "newsletter.emailLabel": "Email",
  "newsletter.subscribe": "Subscribe",
  "newsletter.sending": "Sending…",
  "newsletter.pending": "Almost — check your inbox for a link to confirm.",
  "newsletter.hint":
    "One email to confirm. Nothing is sent until you follow it.",
  "newsletter.error": "That did not go through. Please try again.",
  "newsletter.closed": "Subscribing is not available right now.",
  "newsletter.confirmed.title": "Subscribed",
  "newsletter.confirmed.body":
    "That address is confirmed. The next letter will arrive there.",
  "newsletter.unsubscribed.title": "Unsubscribed",
  "newsletter.unsubscribed.body":
    "That address has been removed. Nothing more will be sent.",
  "newsletter.invalid.title": "That link is not valid",
  "newsletter.invalid.body":
    "It is not a link this site issued, or it has been replaced since.",

  "admin.title": "Admin Dashboard",
  "admin.pendingComments": "Pending Comments",
  "admin.approvedComments": "Approved Comments",
  "admin.subscribers": "Subscribers",
  "admin.approve": "Approve",
  "admin.hide": "Hide",
  "admin.delete": "Delete",
  "admin.spam": "Spam",
  "admin.reply": "Reply",
  "admin.sendNewsletter": "Send Newsletter",
  "admin.status.pending": "Pending",
  "admin.status.approved": "Approved",
  "admin.status.hidden": "Hidden",
  "admin.status.spam": "Spam",
  "admin.status.deleted": "Deleted",
  "admin.refresh": "Refresh",
  "admin.loading": "Loading…",
  "admin.nothingHere": "Nothing {{status}}.",
  "admin.recentActivity": "Recent activity",
  "admin.authorBadge": "author",
  "admin.replyBadge": "reply",
  "admin.reachableBadge": "reachable",
  "admin.reachableHint": "An address was left, so a reply could be delivered.",
  "admin.cancel": "Cancel",
  "admin.replyLabel": "Reply as the site author — published immediately",
  "admin.publishReply": "Publish reply",
  "admin.unauthorised":
    "Not authorised. Sign in through Cloudflare Access, or set ADMIN_TOKEN.",
  "admin.couldNotReach": "Could not reach the API.",
  "admin.requestFailed": "Request failed ({{status}}).",
  "admin.actionFailed": "Action failed ({{status}}).",
  "admin.replyFailed": "Reply failed ({{status}}).",
  "admin.commentStatus": "Comment status",

  "admin.newsletter": "Newsletter",
  "admin.email": "Email",
  "admin.joined": "Joined",
  "admin.noSubscribers": "No subscribers here.",
  "admin.subject": "Subject",
  "admin.bodyHtml": "Body (HTML)",
  "admin.send": "Send",
  "admin.sending": "Sending…",
  "admin.sendResult": "Sent {{sent}}, failed {{failed}}, skipped {{skipped}}.",
  "admin.subscriberStatus.pending": "Pending",
  "admin.subscriberStatus.active": "Active",
  "admin.subscriberStatus.unsubscribed": "Unsubscribed",
  "admin.subscriberStatus.bounced": "Bounced",
  "admin.subscriberStatus.complained": "Complained",

  "error.notFoundTitle": "Page not found",
  "error.notFoundBody": "That card is not on the desk.",

  "common.loading": "Loading...",
  "common.error": "Something went wrong.",
  "common.close": "Close",
  "common.open": "Open",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.yes": "Yes",
  "common.no": "No",
  "common.confirm": "Confirm",
  "common.success": "Success",
};
