import { UIDictionary } from "./types.js";

export const ja: UIDictionary = {
  "nav.home": "ホーム",
  "nav.about": "概要",
  "nav.admin": "管理",
  "nav.search": "検索",
  "nav.back": "戻る",

  "desk.readArticle": "記事を読む",
  "desk.minRead": "分で読める",
  "desk.scrollLeft": "左にスクロール",
  "desk.scrollRight": "右にスクロール",
  "desk.clickToRead": "カードをクリックして読む",
  "desk.focusedCard": "現在のカード",

  "article.back": "戻る",
  "article.share": "共有",
  "article.category": "カテゴリー",
  "article.tags": "タグ",
  "article.published": "公開日",
  "article.updated": "更新日",

  "comment.name": "名前",
  "comment.email": "メール",
  "comment.body": "コメント",
  "comment.submit": "送信",
  "comment.placeholder": "コメントを書く...",
  "comment.noComments": "まだコメントはありません。最初のコメントを書いてみませんか。",
  "comment.pending": "承認待ち",
  "comment.approved": "承認済み",
  "comment.hidden": "非表示",
  "comment.reply": "返信",
  "comment.report": "報告",

  "admin.title": "管理パネル",
  "admin.pendingComments": "承認待ちコメント",
  "admin.approvedComments": "承認済みコメント",
  "admin.subscribers": "購読者",
  "admin.approve": "承認",
  "admin.hide": "非表示",
  "admin.delete": "削除",
  "admin.spam": "スパム",
  "admin.reply": "返信",
  "admin.sendNewsletter": "メールを送信",

  "common.loading": "読み込み中...",
  "common.error": "エラーが発生しました。",
  "common.close": "閉じる",
  "common.open": "開く",
  "common.cancel": "キャンセル",
  "common.save": "保存",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.confirm": "確認",
  "common.success": "成功",
};
