import type { UIDictionary } from "./types.js";

export const ja: UIDictionary = {
  "nav.home": "ホーム",
  "nav.about": "概要",
  "nav.admin": "管理",
  "nav.search": "検索",
  "nav.back": "戻る",

  "desk.readArticle": "記事を読む",
  "desk.minRead": "分で読める",
  "desk.scrollLeft": "左にスクロール",
  "desk.scrollRight": "右にスクロール",
  "desk.clickToRead": "カードをクリックして読む",
  "desk.focusedCard": "現在のカード",

  "article.back": "戻る",
  "article.share": "共有",
  "article.category": "カテゴリー",
  "article.tags": "タグ",
  "article.published": "公開日",
  "article.updated": "更新日",

  "comment.name": "名前",
  "comment.email": "メール",
  "comment.body": "コメント",
  "comment.submit": "送信",
  "comment.placeholder": "コメントを書く...",
  "comment.noComments":
    "まだコメントはありません。最初のコメントを書いてみませんか。",
  "comment.pending": "承認待ち",
  "comment.approved": "承認済み",
  "comment.hidden": "非表示",
  "comment.reply": "返信",
  "comment.report": "報告",
  "comment.title": "コメント",
  "comment.loading": "コメントを読み込んでいます…",
  "comment.posted": "ありがとうございます。コメントは承認待ちです。",
  "comment.emailHint": "任意。公開されません。",
  "comment.closed": "コメントはまだ受け付けていません。",
  "comment.error": "送信できませんでした。もう一度お試しください。",

  "admin.title": "管理パネル",
  "admin.pendingComments": "承認待ちコメント",
  "admin.approvedComments": "承認済みコメント",
  "admin.subscribers": "購読者",
  "admin.approve": "承認",
  "admin.hide": "非表示",
  "admin.delete": "削除",
  "admin.spam": "スパム",
  "admin.reply": "返信",
  "admin.sendNewsletter": "メールを送信",
  "admin.status.pending": "承認待ち",
  "admin.status.approved": "承認済み",
  "admin.status.hidden": "非表示",
  "admin.status.spam": "スパム",
  "admin.status.deleted": "削除済み",
  "admin.refresh": "更新",
  "admin.loading": "読み込み中…",
  "admin.nothingHere": "{{status}}のコメントはありません。",
  "admin.recentActivity": "最近の操作",
  "admin.authorBadge": "作者",
  "admin.replyBadge": "返信",
  "admin.reachableBadge": "連絡可",
  "admin.reachableHint":
    "メールアドレスが残されているため、返信を届けられます。",
  "admin.cancel": "キャンセル",
  "admin.replyLabel": "サイト作者として返信 — すぐに公開されます",
  "admin.publishReply": "返信を公開",
  "admin.unauthorised":
    "権限がありません。Cloudflare Access でサインインするか、ADMIN_TOKEN を設定してください。",
  "admin.couldNotReach": "API に接続できませんでした。",
  "admin.requestFailed": "リクエストに失敗しました（{{status}}）。",
  "admin.actionFailed": "操作に失敗しました（{{status}}）。",
  "admin.replyFailed": "返信に失敗しました（{{status}}）。",
  "admin.commentStatus": "コメントの状態",

  "error.notFoundTitle": "ページが見つかりません",
  "error.notFoundBody": "そのカードは机の上にありません。",

  "common.loading": "読み込み中...",
  "common.error": "エラーが発生しました。",
  "common.close": "閉じる",
  "common.open": "開く",
  "common.cancel": "キャンセル",
  "common.save": "保存",
  "common.yes": "はい",
  "common.no": "いいえ",
  "common.confirm": "確認",
  "common.success": "成功",
};
