import { UIDictionary } from "./types.js";

export const ko: UIDictionary = {
  "nav.home": "홈",
  "nav.about": "소개",
  "nav.admin": "관리",
  "nav.search": "검색",
  "nav.back": "뒤로",

  "desk.readArticle": "글 읽기",
  "desk.minRead": "분 읽기",
  "desk.scrollLeft": "왼쪽으로 스크롤",
  "desk.scrollRight": "오른쪽으로 스크롤",
  "desk.clickToRead": "카드를 클릭하여 읽기",
  "desk.focusedCard": "현재 카드",

  "article.back": "뒤로",
  "article.share": "공유",
  "article.category": "카테고리",
  "article.tags": "태그",
  "article.published": "게시일",
  "article.updated": "수정일",

  "comment.name": "이름",
  "comment.email": "이메일",
  "comment.body": "댓글",
  "comment.submit": "제출",
  "comment.placeholder": "댓글을 작성하세요...",
  "comment.noComments": "아직 댓글이 없습니다. 첫 번째 의견을 공유해 보세요.",
  "comment.pending": "승인 대기 중",
  "comment.approved": "승인됨",
  "comment.hidden": "숨김",
  "comment.reply": "답글",
  "comment.report": "신고",

  "admin.title": "관리 패널",
  "admin.pendingComments": "승인 대기 댓글",
  "admin.approvedComments": "승인된 댓글",
  "admin.subscribers": "구독자",
  "admin.approve": "승인",
  "admin.hide": "숨김",
  "admin.delete": "삭제",
  "admin.spam": "스팸",
  "admin.reply": "답글",
  "admin.sendNewsletter": "메일 발송",

  "common.loading": "로딩 중...",
  "common.error": "문제가 발생했습니다.",
  "common.close": "닫기",
  "common.open": "열기",
  "common.cancel": "취소",
  "common.save": "저장",
  "common.yes": "예",
  "common.no": "아니요",
  "common.confirm": "확인",
  "common.success": "성공",
};
