import type { UIDictionary } from "./types.js";

export const ko: UIDictionary = {
  "nav.home": "홈",
  "nav.about": "소개",
  "nav.admin": "관리",
  "nav.search": "검색",
  "nav.back": "뒤로",

  "desk.readArticle": "글 읽기",
  "desk.minRead": "분 읽기",
  "desk.scrollLeft": "왼쪽으로 스크롤",
  "desk.scrollRight": "오른쪽으로 스크롤",
  "desk.clickToRead": "카드를 클릭하여 읽기",
  "desk.focusedCard": "현재 카드",

  "article.back": "뒤로",
  "article.share": "공유",
  "article.category": "카테고리",
  "article.tags": "태그",
  "article.published": "게시일",
  "article.updated": "수정일",

  "comment.name": "이름",
  "comment.email": "이메일",
  "comment.body": "댓글",
  "comment.submit": "제출",
  "comment.placeholder": "댓글을 작성하세요...",
  "comment.noComments": "아직 댓글이 없습니다. 첫 번째 의견을 공유해 보세요.",
  "comment.pending": "승인 대기 중",
  "comment.approved": "승인됨",
  "comment.hidden": "숨김",
  "comment.reply": "답글",
  "comment.report": "신고",
  "comment.title": "댓글",
  "comment.loading": "댓글을 불러오는 중…",
  "comment.posted": "감사합니다. 댓글이 검토를 기다리고 있습니다.",
  "comment.emailHint": "선택 사항이며 공개되지 않습니다.",
  "comment.closed": "아직 댓글을 받지 않습니다.",
  "comment.error": "전송하지 못했습니다. 다시 시도해 주세요.",

  "newsletter.title": "뉴스레터",
  "newsletter.intro":
    "쓸 만한 것이 있을 때 가끔 보내는 편지입니다. 정해진 주기는 없습니다.",
  "newsletter.emailLabel": "이메일",
  "newsletter.subscribe": "구독하기",
  "newsletter.sending": "보내는 중…",
  "newsletter.pending":
    "거의 다 됐습니다 — 받은편지함에서 확인 링크를 열어 주세요.",
  "newsletter.hint":
    "확인 메일 한 통이 갑니다. 열기 전에는 아무것도 보내지 않습니다.",
  "newsletter.error": "전송되지 않았습니다. 다시 시도해 주세요.",
  "newsletter.closed": "지금은 구독을 받을 수 없습니다.",
  "newsletter.confirmed.title": "구독 확인됨",
  "newsletter.confirmed.body":
    "이 주소가 확인되었습니다. 다음 편지가 여기로 도착합니다.",
  "newsletter.unsubscribed.title": "구독 해지됨",
  "newsletter.unsubscribed.body":
    "이 주소는 목록에서 삭제되었습니다. 더 이상 아무것도 보내지 않습니다.",
  "newsletter.invalid.title": "유효하지 않은 링크",
  "newsletter.invalid.body":
    "이 사이트가 보낸 링크가 아니거나, 더 이상 쓸 수 없습니다.",

  "admin.title": "관리 패널",
  "admin.pendingComments": "승인 대기 댓글",
  "admin.approvedComments": "승인된 댓글",
  "admin.subscribers": "구독자",
  "admin.approve": "승인",
  "admin.hide": "숨김",
  "admin.delete": "삭제",
  "admin.spam": "스팸",
  "admin.reply": "답글",
  "admin.sendNewsletter": "메일 발송",
  "admin.status.pending": "검토 대기",
  "admin.status.approved": "승인됨",
  "admin.status.hidden": "숨김",
  "admin.status.spam": "스팸",
  "admin.status.deleted": "삭제됨",
  "admin.refresh": "새로고침",
  "admin.loading": "불러오는 중…",
  "admin.nothingHere": "{{status}} 댓글이 없습니다.",
  "admin.recentActivity": "최근 활동",
  "admin.authorBadge": "작성자",
  "admin.replyBadge": "답글",
  "admin.reachableBadge": "연락 가능",
  "admin.reachableHint": "이메일이 남아 있어 답글을 보낼 수 있습니다.",
  "admin.cancel": "취소",
  "admin.replyLabel": "사이트 작성자로 답글 — 즉시 게시됩니다",
  "admin.publishReply": "답글 게시",
  "admin.unauthorised":
    "권한이 없습니다. Cloudflare Access로 로그인하거나 ADMIN_TOKEN을 설정하세요.",
  "admin.couldNotReach": "API에 연결할 수 없습니다.",
  "admin.requestFailed": "요청 실패({{status}}).",
  "admin.actionFailed": "작업 실패({{status}}).",
  "admin.replyFailed": "답글 실패({{status}}).",
  "admin.commentStatus": "댓글 상태",

  "admin.newsletter": "뉴스레터",
  "admin.email": "이메일",
  "admin.joined": "가입일",
  "admin.noSubscribers": "아직 구독자가 없습니다.",
  "admin.subject": "제목",
  "admin.bodyHtml": "본문(HTML)",
  "admin.send": "보내기",
  "admin.sending": "보내는 중…",
  "admin.sendResult":
    "{{sent}}건 발송, {{failed}}건 실패, {{skipped}}건 건너뜀.",
  "admin.subscriberStatus.pending": "확인 대기",
  "admin.subscriberStatus.active": "활성",
  "admin.subscriberStatus.unsubscribed": "해지됨",
  "admin.subscriberStatus.bounced": "반송",
  "admin.subscriberStatus.complained": "스팸 신고",

  "error.notFoundTitle": "페이지를 찾을 수 없습니다",
  "error.notFoundBody": "그 카드는 책상 위에 없습니다.",

  "common.loading": "로딩 중...",
  "common.error": "문제가 발생했습니다.",
  "common.close": "닫기",
  "common.open": "열기",
  "common.cancel": "취소",
  "common.save": "저장",
  "common.yes": "예",
  "common.no": "아니요",
  "common.confirm": "확인",
  "common.success": "성공",
};
