import type { UIDictionary } from "./types.js";

export const zhHans: UIDictionary = {
  "nav.home": "首页",
  "nav.about": "关于",
  "nav.admin": "管理",
  "nav.search": "搜索",
  "nav.back": "返回",

  "desk.readArticle": "阅读文章",
  "desk.minRead": "分钟阅读",
  "desk.scrollLeft": "向左滚动",
  "desk.scrollRight": "向右滚动",
  "desk.clickToRead": "点击卡片阅读",
  "desk.focusedCard": "当前卡片",

  "article.back": "返回",
  "article.share": "分享",
  "article.category": "分类",
  "article.tags": "标签",
  "article.published": "发布于",
  "article.updated": "更新于",

  "comment.name": "姓名",
  "comment.email": "邮箱",
  "comment.body": "评论",
  "comment.submit": "提交",
  "comment.placeholder": "写下你的评论...",
  "comment.noComments": "暂无评论。来做第一个分享想法的人吧。",
  "comment.pending": "等待审核",
  "comment.approved": "已通过",
  "comment.hidden": "已隐藏",
  "comment.reply": "回复",
  "comment.report": "举报",

  "admin.title": "管理面板",
  "admin.pendingComments": "待审核评论",
  "admin.approvedComments": "已批准评论",
  "admin.subscribers": "订阅者",
  "admin.approve": "批准",
  "admin.hide": "隐藏",
  "admin.delete": "删除",
  "admin.spam": "垃圾",
  "admin.reply": "回复",
  "admin.sendNewsletter": "发送邮件",

  "common.loading": "加载中...",
  "common.error": "出错了。",
  "common.close": "关闭",
  "common.open": "打开",
  "common.cancel": "取消",
  "common.save": "保存",
  "common.yes": "是",
  "common.no": "否",
  "common.confirm": "确认",
  "common.success": "成功",
};
