import type { UIDictionary } from "./types.js";

export const zhHant: UIDictionary = {
  "nav.home": "首頁",
  "nav.about": "關於",
  "nav.admin": "管理",
  "nav.search": "搜尋",
  "nav.back": "返回",

  "desk.readArticle": "閱讀文章",
  "desk.minRead": "分鐘閱讀",
  "desk.scrollLeft": "向左捲動",
  "desk.scrollRight": "向右捲動",
  "desk.clickToRead": "點擊卡片閱讀",
  "desk.focusedCard": "當前卡片",

  "article.back": "返回",
  "article.share": "分享",
  "article.category": "分類",
  "article.tags": "標籤",
  "article.published": "發布於",
  "article.updated": "更新於",

  "comment.name": "姓名",
  "comment.email": "電郵",
  "comment.body": "評論",
  "comment.submit": "提交",
  "comment.placeholder": "寫下你的評論...",
  "comment.noComments": "暫無評論。來做第一個分享想法的人吧。",
  "comment.pending": "等待審核",
  "comment.approved": "已通過",
  "comment.hidden": "已隱藏",
  "comment.reply": "回覆",
  "comment.report": "舉報",
  "comment.title": "留言",
  "comment.loading": "正在載入留言…",
  "comment.posted": "謝謝，你的留言正在等待審核。",
  "comment.emailHint": "選填，不會公開。",
  "comment.closed": "留言功能尚未開放。",
  "comment.error": "送出失敗，請再試一次。",

  "newsletter.title": "通訊",
  "newsletter.intro": "偶爾寫下的信。沒有固定頻率。",
  "newsletter.emailLabel": "電子郵件",
  "newsletter.subscribe": "訂閱",
  "newsletter.sending": "傳送中…",
  "newsletter.pending": "就差一步——請到信箱點擊確認連結。",
  "newsletter.hint": "會先收到一封確認信，確認之前不會寄出任何內容。",
  "newsletter.error": "沒有送出，請再試一次。",
  "newsletter.closed": "暫時無法訂閱。",
  "newsletter.confirmed.title": "已確認",
  "newsletter.confirmed.body": "這個信箱已確認訂閱，下一封信會寄到這裡。",
  "newsletter.unsubscribed.title": "已取消訂閱",
  "newsletter.unsubscribed.body": "這個信箱已從名單移除，不會再收到任何郵件。",
  "newsletter.invalid.title": "連結無效",
  "newsletter.invalid.body": "這不是本站發出的連結，或者它已經失效。",

  "admin.title": "管理面板",
  "admin.pendingComments": "待審核評論",
  "admin.approvedComments": "已批准評論",
  "admin.subscribers": "訂閱者",
  "admin.approve": "批准",
  "admin.hide": "隱藏",
  "admin.delete": "刪除",
  "admin.spam": "垃圾",
  "admin.reply": "回覆",
  "admin.sendNewsletter": "發送郵件",
  "admin.status.pending": "待審核",
  "admin.status.approved": "已通過",
  "admin.status.hidden": "已隱藏",
  "admin.status.spam": "垃圾",
  "admin.status.deleted": "已刪除",
  "admin.refresh": "重新整理",
  "admin.loading": "載入中…",
  "admin.nothingHere": "沒有{{status}}的留言。",
  "admin.recentActivity": "最近操作",
  "admin.authorBadge": "作者",
  "admin.replyBadge": "回覆",
  "admin.reachableBadge": "可聯絡",
  "admin.reachableHint": "對方留下了信箱，可以回覆通知。",
  "admin.cancel": "取消",
  "admin.replyLabel": "以站點作者身分回覆 —— 立即發布",
  "admin.publishReply": "發布回覆",
  "admin.unauthorised":
    "未授權。請透過 Cloudflare Access 登入，或設定 ADMIN_TOKEN。",
  "admin.couldNotReach": "無法連線到 API。",
  "admin.requestFailed": "請求失敗（{{status}}）。",
  "admin.actionFailed": "操作失敗（{{status}}）。",
  "admin.replyFailed": "回覆失敗（{{status}}）。",
  "admin.commentStatus": "留言狀態",

  "error.notFoundTitle": "頁面不存在",
  "error.notFoundBody": "這張卡片不在桌面上。",

  "common.loading": "載入中...",
  "common.error": "出錯了。",
  "common.close": "關閉",
  "common.open": "打開",
  "common.cancel": "取消",
  "common.save": "儲存",
  "common.yes": "是",
  "common.no": "否",
  "common.confirm": "確認",
  "common.success": "成功",
};
