import type { UIDictionary } from "./types.js";

export const zhHant: UIDictionary = {
  "nav.home": "首頁",
  "nav.about": "關於",
  "nav.admin": "管理",
  "nav.search": "搜尋",
  "nav.back": "返回",

  "desk.readArticle": "閱讀文章",
  "desk.minRead": "分鐘閱讀",
  "desk.scrollLeft": "向左捲動",
  "desk.scrollRight": "向右捲動",
  "desk.clickToRead": "點擊卡片閱讀",
  "desk.focusedCard": "當前卡片",

  "article.back": "返回",
  "article.share": "分享",
  "article.category": "分類",
  "article.tags": "標籤",
  "article.published": "發布於",
  "article.updated": "更新於",

  "comment.name": "姓名",
  "comment.email": "電郵",
  "comment.body": "評論",
  "comment.submit": "提交",
  "comment.placeholder": "寫下你的評論...",
  "comment.noComments": "暫無評論。來做第一個分享想法的人吧。",
  "comment.pending": "等待審核",
  "comment.approved": "已通過",
  "comment.hidden": "已隱藏",
  "comment.reply": "回覆",
  "comment.report": "舉報",

  "admin.title": "管理面板",
  "admin.pendingComments": "待審核評論",
  "admin.approvedComments": "已批准評論",
  "admin.subscribers": "訂閱者",
  "admin.approve": "批准",
  "admin.hide": "隱藏",
  "admin.delete": "刪除",
  "admin.spam": "垃圾",
  "admin.reply": "回覆",
  "admin.sendNewsletter": "發送郵件",

  "common.loading": "載入中...",
  "common.error": "出錯了。",
  "common.close": "關閉",
  "common.open": "打開",
  "common.cancel": "取消",
  "common.save": "儲存",
  "common.yes": "是",
  "common.no": "否",
  "common.confirm": "確認",
  "common.success": "成功",
};
