import type { UIDictionary } from "./types.js";

export const zhHans: UIDictionary = {
  "nav.home": "首页",
  "nav.about": "关于",
  "nav.admin": "管理",
  "nav.search": "搜索",
  "nav.back": "返回",

  "desk.readArticle": "阅读文章",
  "desk.minRead": "分钟阅读",
  "desk.scrollLeft": "向左滚动",
  "desk.scrollRight": "向右滚动",
  "desk.clickToRead": "点击卡片阅读",
  "desk.focusedCard": "当前卡片",

  "article.back": "返回",
  "article.share": "分享",
  "article.category": "分类",
  "article.tags": "标签",
  "article.published": "发布于",
  "article.updated": "更新于",

  "comment.name": "姓名",
  "comment.email": "邮箱",
  "comment.body": "评论",
  "comment.submit": "提交",
  "comment.placeholder": "写下你的评论...",
  "comment.noComments": "暂无评论。来做第一个分享想法的人吧。",
  "comment.pending": "等待审核",
  "comment.approved": "已通过",
  "comment.hidden": "已隐藏",
  "comment.reply": "回复",
  "comment.report": "举报",
  "comment.title": "评论",
  "comment.loading": "正在加载评论…",
  "comment.posted": "谢谢，你的评论正在等待审核。",
  "comment.emailHint": "可选，不会公开。",
  "comment.closed": "评论功能尚未开放。",
  "comment.error": "提交失败，请重试。",

  "newsletter.title": "通讯",
  "newsletter.intro": "偶尔写下的信。没有固定频率。",
  "newsletter.emailLabel": "邮箱",
  "newsletter.subscribe": "订阅",
  "newsletter.sending": "发送中…",
  "newsletter.pending": "就差一步——请到邮箱里点击确认链接。",
  "newsletter.hint": "会先收到一封确认邮件，确认之前不会发送任何内容。",
  "newsletter.error": "没有发送成功，请再试一次。",
  "newsletter.closed": "暂时无法订阅。",
  "newsletter.confirmed.title": "已确认",
  "newsletter.confirmed.body": "这个邮箱已确认订阅，下一封信会寄到这里。",
  "newsletter.unsubscribed.title": "已退订",
  "newsletter.unsubscribed.body":
    "这个邮箱已从名单中移除，不会再收到任何邮件。",
  "newsletter.invalid.title": "链接无效",
  "newsletter.invalid.body": "这不是本站发出的链接，或者它已经失效。",

  "admin.title": "管理面板",
  "admin.pendingComments": "待审核评论",
  "admin.approvedComments": "已批准评论",
  "admin.subscribers": "订阅者",
  "admin.approve": "批准",
  "admin.hide": "隐藏",
  "admin.delete": "删除",
  "admin.spam": "垃圾",
  "admin.reply": "回复",
  "admin.sendNewsletter": "发送邮件",
  "admin.status.pending": "待审核",
  "admin.status.approved": "已通过",
  "admin.status.hidden": "已隐藏",
  "admin.status.spam": "垃圾",
  "admin.status.deleted": "已删除",
  "admin.refresh": "刷新",
  "admin.loading": "加载中…",
  "admin.nothingHere": "没有{{status}}的评论。",
  "admin.recentActivity": "最近操作",
  "admin.authorBadge": "作者",
  "admin.replyBadge": "回复",
  "admin.reachableBadge": "可联系",
  "admin.reachableHint": "对方留下了邮箱，可以回复通知。",
  "admin.cancel": "取消",
  "admin.replyLabel": "以站点作者身份回复 —— 立即发布",
  "admin.publishReply": "发布回复",
  "admin.unauthorised":
    "未授权。请通过 Cloudflare Access 登录，或设置 ADMIN_TOKEN。",
  "admin.couldNotReach": "无法连接到 API。",
  "admin.requestFailed": "请求失败（{{status}}）。",
  "admin.actionFailed": "操作失败（{{status}}）。",
  "admin.replyFailed": "回复失败（{{status}}）。",
  "admin.commentStatus": "评论状态",

  "admin.newsletter": "通讯",
  "admin.email": "邮箱",
  "admin.joined": "加入时间",
  "admin.noSubscribers": "这里还没有订阅者。",
  "admin.subject": "主题",
  "admin.bodyHtml": "正文（HTML）",
  "admin.send": "发送",
  "admin.sending": "发送中…",
  "admin.sendResult":
    "已发送 {{sent}} 封，失败 {{failed}} 封，跳过 {{skipped}} 封。",
  "admin.subscriberStatus.pending": "待确认",
  "admin.subscriberStatus.active": "已确认",
  "admin.subscriberStatus.unsubscribed": "已退订",
  "admin.subscriberStatus.bounced": "退信",
  "admin.subscriberStatus.complained": "标记为垃圾邮件",

  "error.notFoundTitle": "页面不存在",
  "error.notFoundBody": "这张卡片不在桌面上。",

  "common.loading": "加载中...",
  "common.error": "出错了。",
  "common.close": "关闭",
  "common.open": "打开",
  "common.cancel": "取消",
  "common.save": "保存",
  "common.yes": "是",
  "common.no": "否",
  "common.confirm": "确认",
  "common.success": "成功",
};
